name: Build and Publish Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/wsus-dashboard

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Prepare tags for Docker image
      - name: Prepare tags
        id: prep
        run: |
          $VERSION = ""
          if ("${{ github.ref }}" -like "refs/tags/v*") {
            $VERSION = "${{ github.ref }}".Replace('refs/tags/v', '')
          } elseif ("${{ github.ref }}" -eq "refs/heads/main" -or "${{ github.ref }}" -eq "refs/heads/master") {
            $VERSION = "latest"
          } else {
            $VERSION = "${{ github.sha }}".Substring(0, 7)
          }
          
          $TAGS = "sappkevin:$VERSION"
          if ($VERSION -eq "latest") {
            $TAGS = "$TAGS,sappkevin:${{ github.sha }}".Substring(0, 7)
          }
          
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
          echo "tags=$TAGS" >> $env:GITHUB_OUTPUT
          
          echo "Building Docker image with tags: $TAGS"

      # Build the Docker image directly with standard Docker commands
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.version }} .

      # Push the image if this is a push event (not a pull request)
      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
            docker push sappkevin/wsus-dashboard:${{ steps.prep.outputs.version }}
          
